import { NextRequest, NextResponse } from "next/server";
import { getIronSession } from "iron-session";
import { sessionOptions, SessionData } from "@/lib/session";
import { cookies } from "next/headers";
import { db } from "@/db";
import { students } from "@/db/schema";
import bcrypt from "bcryptjs";

export async function POST(req: NextRequest) {
  const { name, email, password } = await req.json();
  const session = await getIronSession<SessionData>(cookies(), sessionOptions);

  try {
    const passwordHash = await bcrypt.hash(password, 10);
    const result = await db.insert(students).values({
      name,
      email,
      passwordHash,
    });

    // In MySQL, insert result doesn't usually return the inserted row directly with drizzle
    // We can fetch it or just use the data we have if we know the ID (UUID generated in DB or client)
    // Actually, our schema uses crypto.randomUUID() as default in drizzle-orm, so it's generated by drizzle if not provided.
    
    // For simplicity, let's just re-fetch or assume it's created if no error
    const newStudent = await db.query.students.findFirst({
      where: (students, { eq }) => eq(students.email, email),
    });

    if (!newStudent) throw new Error("Registration failed");

    session.userId = newStudent.id;
    session.role = "student";
    session.name = newStudent.name;
    session.email = newStudent.email;
    await session.save();

    return NextResponse.json({ success: true, data: { name: newStudent.name, role: "student" } });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
